title: general organization overview
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: # the name of the repository when it is created for the learner
  repo: # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
 Step 1: # general navigation and overview of what orgs are; learner create org 
- title: your first organization
  description: In this step, you will create your very first organization and explore benefits of an organization.
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

 Step 2: # admin setup; basic admin of org; learner review initial setup and modify profile
- title: administration to your organization
  description: In this step, we will review basic admin setup including and overview of settings # and including making your org better with apps?
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

 Step 3: # people management; adding users, assigning permissions; learner invite user and assign permission
 - title: building your organization
  description: In this step, we will review how to add users to your organization and assign them permission
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

 Step 4: # team management, nesting teams, assigning teams; user create team 1+2, user nest team 2-1, user assign team 1
 - title: organizing your organization
  description: In this step, we will discuss creating teams of organization users and assigning roles to teams
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

 Step 5:  # repo creation, assigning repos, repo access; learner init repo with README and assign team to repo
 - title: developing your organization
  description: In this step, we will discuss initializing a code repository and assigning teams and permissions for the repository
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

 Step 6: # pro tips/best practices/QOL/Do&DoNot list
 - title: best practices # no clue for step name really
  description: In this step, we will be reviewing some of the best practices for organizations such as security, github apps/API/Webhooks, auditing of your organization
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions
